import defaultImage from "../assets/images/defaultimage.jpg";
import defaultImage2 from "../assets/images/defaultimage2.jpg";
import defaultImage3 from "../assets/images/defaultimage3.jpg";
import defaultImage4 from "../assets/images/defaultimage4.jpg";
export default [
  {
    id: 1,
    path: "house-designs",
    src: defaultImage,
    title: "3 bedroom 2 bedroom house designs - ID 13228",
    price: "$349.00",
    desc1: "1 story",
    desc2: "2 baths",
    desc3: "3 bedrooms",
    desc4: "225 sq m",
    desc5: "length 16m",
    desc6: "width 17m",
  },
  {
    id: 2,
    path: "house-designs",
    src: defaultImage2,
    title: "2 bedroom 3 bedroom house designs - ID 13228",
    price: "$349.00",
    desc1: "2 stories",
    desc2: "2 baths",
    desc3: "3 bedrooms",
    desc4: "225 sq m",
    desc5: "length 16m",
    desc6: "width 17m",
  },
  {
    id: 3,
    path: "house-designs",
    src: defaultImage3,
    title: "3 bedroom 2 bedroom house designs - ID 13228",
    price: "$349.00",
    desc1: "1 story",
    desc2: "2 baths",
    desc3: "3 bedrooms",
    desc4: "225 sq m",
    desc5: "length 16m",
    desc6: "width 17m",
  },
  {
    id: 4,
    path: "house-designs",
    src: defaultImage4,
    title: "3 bedroom 2 bedroom house designs - ID 13228",
    price: "$349.00",
    desc1: "1 story",
    desc2: "2 baths",
    desc3: "3 bedrooms",
    desc4: "225 sq m",
    desc5: "length 16m",
    desc6: "width 17m",
  },
  {
    id: 5,
    path: "house-designs",
    src: defaultImage3,
    title: "3 bedroom 2 bedroom house designs - ID 13228",
    price: "$349.00",
    desc1: "1 story",
    desc2: "2 baths",
    desc3: "3 bedrooms",
    desc4: "225 sq m",
    desc5: "length 16m",
    desc6: "width 17m",
  },
  {
    id: 6,
    path: "house-designs",
    src: defaultImage2,
    title: "3 bedroom 2 bedroom house designs - ID 13228",
    price: "$349.00",
    desc1: "1 story",
    desc2: "2 baths",
    desc3: "3 bedrooms",
    desc4: "225 sq m",
    desc5: "length 16m",
    desc6: "width 17m",
  },
];
